TRAIN_CONFIGS:
  out_dir: ${model_config.NAME}_${DATASET_CONFIGS.data_type}
  lr: 1e-4
  iterations: 10000
  save_interval: 1000
  val_interval: 1000

DATASET_CONFIGS:
  data_type: video
  video_file: data/cat.npy
  normalize: True
  batch_size: 262144

defaults:
  - model_config: siren

# hydra logging
hydra:
  run:
    dir: outputs/${TRAIN_CONFIGS.out_dir}/hydra_configs/${now:%Y-%m-%d-%H-%M-%S}
    
  sweep:
    dir: outputs/${TRAIN_CONFIGS.out_dir}/hydra_configs/${now:%Y-%m-%d-%H-%M-%S}/${hydra.job.name}
    subdir: ${hydra.job.num}